# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TEAM2OARS_APP', '0002_auto_20160416_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('apt_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('apt_type', models.CharField(max_length=1)),
                ('apt_status', models.CharField(choices=[('V', 'Vacant'), ('R', 'Rented')], default='V', max_length=6)),
                ('apt_utility', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3)),
                ('apt_deposit_amt', models.FloatField(max_length=5)),
                ('apt_rent_amt', models.FloatField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Automobiles',
            fields=[
                ('license_no', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('auto_make', models.TextField(max_length=20)),
                ('auto_model', models.CharField(max_length=20)),
                ('auto_year', models.DateField()),
                ('auto_color', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('complaint_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('complaint_date', models.DateField()),
                ('rental_complaint', models.TextField()),
                ('apt_complaint', models.TextField()),
                ('status', models.CharField(choices=[('F', 'Fixed'), ('P', 'Pending'), ('Null', 'Undetermined')], default='Null', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Handle_Rents',
            fields=[
                ('rental_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('rental_date', models.DateField()),
                ('rental_status', models.CharField(choices=[('S', 'Signed but Not Occupied'), ('O', 'Occupied')], default='S', max_length=50)),
                ('cancel_date', models.DateField()),
                ('lease_type', models.CharField(choices=[('one', 'One'), ('six', 'Six')], default='one', max_length=50)),
                ('lease_start', models.DateField()),
                ('lease_end', models.DateField()),
                ('renewal_date', models.DateField()),
                ('complaint_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TEAM2OARS_APP.Complaints')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField()),
                ('invoice_due', models.FloatField(max_length=5)),
                ('CC_no', models.BigIntegerField()),
                ('CC_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('american express', 'American Express'), ('discover', 'Discover')], default='visa', max_length=30)),
                ('CC_exp_date', models.DateField()),
                ('CC_amt', models.FloatField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('position', models.CharField(choices=[('Assistant', 'assistant'), ('Manager', 'manager'), ('Supervisor', 'supervisor'), ('Customer Service', 'customer service')], default='Assistant', max_length=16)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('salary', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_ss', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tenant_name', models.TextField()),
                ('tenant_DOB', models.DateField()),
                ('marital', models.CharField(choices=[('M', 'Married'), ('S', 'Single')], default='S', max_length=15)),
                ('work_phone', models.PositiveIntegerField()),
                ('home_phone', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('employer', models.TextField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant_Family',
            fields=[
                ('family_ss', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('spouse', models.TextField()),
                ('child', models.TextField()),
                ('divorced', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3)),
                ('single', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('tenant_ss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TEAM2OARS_APP.Tenant')),
            ],
        ),
        migrations.AlterField(
            model_name='testimonies',
            name='tenant_ss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TEAM2OARS_APP.Tenant'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='tenant_ss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TEAM2OARS_APP.Tenant'),
        ),
        migrations.AddField(
            model_name='handle_rents',
            name='staff_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TEAM2OARS_APP.Staff'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='tenant_ss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TEAM2OARS_APP.Tenant'),
        ),
        migrations.AddField(
            model_name='automobiles',
            name='tenant_ss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TEAM2OARS_APP.Tenant'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenant_ss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TEAM2OARS_APP.Tenant'),
        ),
    ]
