# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-24 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEAM2OARS_APP', '0004_auto_20160424_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tenant_ss',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
