# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-30 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEAM2OARS_APP', '0011_auto_20160429_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobiles',
            name='auto_year',
            field=models.TextField(),
        ),
    ]
