# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEAM2OARS_APP', '0012_auto_20160430_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handle_rents',
            name='rental_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
