# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEAM2OARS_APP', '0013_auto_20160501_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='marital',
            field=models.CharField(max_length=1),
        ),
    ]
