# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEAM2OARS_APP', '0015_auto_20160501_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complaint_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
