# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEAM2OARS_APP', '0016_auto_20160502_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('F', 'Fixed'), ('P', 'Pending'), ('Null', 'Undetermined')], max_length=30),
        ),
    ]
