# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEAM2OARS_APP', '0019_auto_20160502_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_no',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
