# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEAM2OARS_APP', '0021_auto_20160502_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apt_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
